import './globals.css'
import type {Metadata} from 'next'
import Link from "next/link";


export const metadata: Metadata = {
    title: 'Learn Next.js',
    description: 'Generated by Neighbor Kim',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html>
        <body>
        {/* a에서 Link로 변경시 로드가 미리되므로 SPA 구현할 수 있음*/}
        <h1><Link href="/">WEB</Link></h1>
        <ol>
            <li><Link href="/read/1">html</Link></li>
            <li><Link href="/read/2">css</Link></li>
        </ol>
        {children}
        <ul>
            <li><Link href="/create">Create</Link></li>
            <li><Link href="/update/1">Update</Link></li>
            <li><input type="button" value="delete"/></li>
        </ul>
        </body>
        </html>
    )
}
